#!/bin/sh
if [ $# -ne 3 ]; then
    echo [ERROR]:Input ERROR
    exit 1
else
    NOW_DIR=$(pwd)
    TMP=$(readlink /usr/local/bin/abd)
    ABD_DIR=${TMP%/abd}

    cp $NOW_DIR/$2/* $ABD_DIR/$1/src
    echo name=${3} > $ABD_DIR/info.env
    cd $ABD_DIR
    docker-compose run --rm $1

    echo ""
    echo "BUILD COMPLETE!"
    echo ""
    echo "###########  OUTPUT  ##########"
    cat $ABD_DIR/$1/src/output.txt
    echo "############# END #############"

    rm -r $ABD_DIR/$1/src
    cp -fr $ABD_DIR/$1/original_src $ABD_DIR/$1/src
    rm $ABD_DIR/info.env
    touch $ABD_DIR/info.env
fi