#!/bin/sh
VERSION="beta1.1"
YEAR="2021"
CNT=0
INPUT=0

usage() {
    echo "Usage: abd [OPTIONS] (LANGUAGE) (DIRECTORY) (FILE)"
    echo "  -h, --help      : Print help message."
    echo "  -v, --version   : Print version infomation."
    echo "  -i              : Read input.txt."
    exit 0
}

version() {
    echo "### SOFTWARE INFOMATION ###"
    echo "Auto build (abd)"
    echo "Version:$VERSION"
    echo ""
    echo "Copyright (C) $YEAR Midori Ado"
    echo "Licensed under the MIT License."
    echo ""
    echo "### MORE INFOMATION ###"
    echo "GitHub page: https://github.com/rp-agota/auto-build"
    exit 0
}

for OPT in "$@"
do
    case $OPT in
        -h | --help)
            usage
            ;;

        -v | --version)
            version
            ;;
        
        -i)
            INPUT=1
            shift
            ;;
        
        -*)
            echo "Unknown option: $1" 1>&2
            exit 1
            ;;
        
        *)
            CNT=$((CNT+1))
            case $CNT in
                1)
                    LANGUAGE=$1
                    ;;
                2)
                    DIRECTORY=$1
                    ;;
                3)
                    FILE=$1
                    ;;
            esac
            shift
            ;;
    esac

done

if [ $CNT -lt 3 ]; then
    echo [ERROR]:Input ERROR
    exit 1
else
    NOW_DIR=$(pwd)
    TMP=$(readlink /usr/local/bin/abd)
    ABD_DIR=${TMP%/abd}

    cp $NOW_DIR/$DIRECTORY/* $ABD_DIR/$LANGUAGE/src
    echo name=${FILE} > $ABD_DIR/info.env
    if [ $INPUT -eq 1 ]; then
        echo input=1 >> $ABD_DIR/info.env
    else
        echo input=0 >> $ABD_DIR/info.env
    fi
    cd $ABD_DIR
    docker-compose run --rm $LANGUAGE

    echo ""
    echo "BUILD COMPLETE!"
    echo ""
    echo "###########  OUTPUT  ##########"
    cat $ABD_DIR/$LANGUAGE/src/output.txt
    echo "############# END #############"

    rm -r $ABD_DIR/$LANGUAGE/src
    cp -fr $ABD_DIR/$LANGUAGE/original_src $ABD_DIR/$LANGUAGE/src
    rm $ABD_DIR/info.env
    touch $ABD_DIR/info.env
fi