version: '3.7'
services: 
        gcc: 
            restart: always
            build: .
            env_file: 
                - info.env
            container_name: 'gcc'
            tty: true
            volumes: 
                - ./src:/root/main