version: '3.7'
services: 
          cpp: 
            build: .
            env_file: 
                - info.env
            container_name: 'C++_ABD_PROCESS'
            tty: true
            volumes: 
                - ./src:/root/main