name: CI

on: 
  push: 
    branches: [ master ]
  pull_request: 
    branches: [ master ]

jobs: 
  Ubuntu: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: init
        run: |
          docker version
          docker-compose version
          make -v
          gcc -v
          
      - name: install
        run: make install

      - name: help
        run: abd -h

      - name: version
        run: abd -v
        
      - name: c-test
        working-directory: ./.test
        run: abd c src test
        
      - name: c++-test
        working-directory: ./.test
        run: abd cpp src test
        
        - name: ALGOL-test
        working-directory: ./.test
        run: abd alg src test
        
      - name: uninstall
        run: make uninstall
