name: CI

on: 
  push: 
    branches: [ master ]
  pull_request: 
    branches: [ master ]

jobs: 
  Ubuntu: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install auto-build
        run: make install
      - name: test
        run: |
          cd .test/
          abd src test
      - name: Uninstall
      - run: make uninstall
