name: CI

on: 
  push: 
    branches: [ master ]
  pull_request: 
    branches: [ master ]

jobs: 
  Ubuntu: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: init
        run: |
          docker version
          docker-compose version
          make -v
          gcc -v
          
      - name: install
        run: make install

      - name: help
        run: abd -h

      - name: version
        run: abd -v
        
      - name: c-test(standard)
        working-directory: ./.test
        run: abd c standard test

      - name: c-test(input)
        working-directory: ./.test
        run: abd -i c input test

      - name: cpp-test(standard)
        working-directory: ./.test
        run: abd cpp standard test

      - name: cpp-test(input)
        working-directory: ./.test
        run: abd -i cpp input test

      - name: uninstall
        run: make uninstall
