name: CI

on: 
  push: 
    branches: [ master ]
  pull_request: 
    branches: [ master ]

jobs: 
  Ubuntu: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Apt check
        run: |
          docker version
          docker-compose version
          make -v
          gcc -v
      - name: install
        run: make install

      - name: test
        working-directory: ./.test
        run: abd src test

      - name: uninstall
        run: make uninstall
