name: CI

on: 
  push: 
    branches: [ master ]
  pull_request: 
    branches: [ master ]

jobs: 
  Ubuntu: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: check
        run: |
          docker version
          docker-compose version
          make -v
          gcc -v
